In [1]:
import numpy as np
import pandas as pd

In [2]:
x_train = pd.read_feather("Data/x_train__IterativeImputer_10itrs.ftr")
x_test = pd.read_feather("Data/x_test__IterativeImputer_10itrs.ftr")

y_train = pd.read_csv("Data/train_y.csv")
y_test = pd.read_csv("Data/Sample_Output.csv", names = ['ID', 'Target'], header=None)

In [28]:
# orig_train = pd.read_csv("Data/train_allx.csv")
# orig_train.drop("ID", axis=1, inplace=True)
orig_test = pd.read_csv("Data/val_allx.csv")
orig_test.drop("ID", axis=1, inplace=True)

In [4]:
orig_train.dtypes[orig_train.dtypes!='float']

D_36     object
D_44     object
B_41      int64
D_130     int64
dtype: object

In [5]:
cols_not_floats = ['D_36', 'D_44', 'B_41', 'D_130']

In [6]:
x_train

,B_37,S_24,S_4,S_14,B_25,D_38,B_30,D_138,P_2,S_7,...,S_5,D_36_CO,D_36_CR,D_36_XL,D_36_XM,D_36_XZ,D_36_nan,D_44_R,D_44_U,D_44_nan
0,0.006462,0.008118,0.853027,0.556641,1.003906,0.193557,0.021301,0.511230,1.004883,0.081543,...,0.004307,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.007748,0.006310,0.758301,0.686035,0.001836,0.189822,0.088501,0.557129,0.687988,0.353027,...,0.009224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.005405,0.005219,0.766602,0.284668,1.002930,0.182655,0.005821,0.854980,0.927734,0.059479,...,0.009636,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.004135,0.000032,0.363281,0.004623,0.533691,0.170661,0.002443,0.526367,0.700684,0.334473,...,0.007523,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.002968,0.002892,0.757324,0.427734,1.001953,0.213928,0.008247,0.820312,1.001953,0.144287,...,0.000535,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458908,0.003967,0.005070,0.167480,0.421143,0.697266,0.186495,0.059113,0.526855,0.852051,0.724121,...,0.001259,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
458909,0.006248,0.007683,0.003338,0.006954,1.004883,0.180386,0.001700,0.575195,0.885254,0.286364,...,0.003376,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
458910,0.004993,0.003204,0.167114,0.289307,0.650879,0.178694,0.007294,0.406738,0.632324,0.346924,...,0.007114,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
458911,0.002348,0.005432,0.330078,0.003138,0.689941,0.184077,0.001930,0.417969,0.846191,0.172607,...,0.003271,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
458912,0.009079,0.009773,0.000458,0.004875,1.001953,0.172941,0.007450,0.602051,0.715332,0.281413,...,0.007168,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [7]:
colstartswith_dict = {}
for col in orig_train.drop(['D_36', 'D_44', 'B_41', 'D_130'], axis=1).columns:
    if col[0] not in colstartswith_dict:
        colstartswith_dict[col[0]] = [col]
    else:
        colstartswith_dict[col[0]].append(col)

In [8]:
colstartswith_dict

{'B': ['B_37',
  'B_25',
  'B_30',
  'B_28',
  'B_42',
  'B_17',
  'B_1',
  'B_31',
  'B_33',
  'B_3',
  'B_19',
  'B_12',
  'B_21',
  'B_29',
  'B_26',
  'B_5',
  'B_9',
  'B_10',
  'B_18',
  'B_4',
  'B_40',
  'B_32',
  'B_14',
  'B_20',
  'B_35',
  'B_24',
  'B_8',
  'B_6',
  'B_38',
  'B_36',
  'B_23',
  'B_2',
  'B_13',
  'B_34',
  'B_7',
  'B_39',
  'B_22',
  'B_15',
  'B_11'],
 'S': ['S_24',
  'S_4',
  'S_14',
  'S_7',
  'S_25',
  'S_12',
  'S_21',
  'S_20',
  'S_13',
  'S_15',
  'S_23',
  'S_3',
  'S_22',
  'S_9',
  'S_16',
  'S_8',
  'S_11',
  'S_26',
  'S_2',
  'S_19',
  'S_5'],
 'D': ['D_38',
  'D_138',
  'D_99',
  'D_121',
  'D_107',
  'D_79',
  'D_60',
  'D_122',
  'D_2',
  'D_15',
  'D_68',
  'D_89',
  'D_8',
  'D_110',
  'D_74',
  'D_17',
  'D_106',
  'D_19',
  'D_88',
  'D_48',
  'D_34',
  'D_98',
  'D_92',
  'D_25',
  'D_59',
  'D_126',
  'D_1',
  'D_90',
  'D_73',
  'D_105',
  'D_67',
  'D_10',
  'D_40',
  'D_27',
  'D_64',
  'D_133',
  'D_50',
  'D_69',
  'D_65',
  'D_129',
  'D_22',
  'D_6',
  'D_56',
  'D_100',
  'D_141',
  'D_87',
  'D_51',
  'D_123',
  'D_84',
  'D_18',
  'D_23',
  'D_55',
  'D_108',
  'D_7',
  'D_135',
  'D_11',
  'D_139',
  'D_142',
  'D_31',
  'D_95',
  'D_61',
  'D_86',
  'D_5',
  'D_117',
  'D_93',
  'D_54',
  'D_20',
  'D_102',
  'D_91',
  'D_32',
  'D_49',
  'D_26',
  'D_124',
  'D_47',
  'D_9',
  'D_70',
  'D_83',
  'D_120',
  'D_80',
  'D_97',
  'D_12',
  'D_132',
  'D_114',
  'D_101',
  'D_96',
  'D_39',
  'D_43',
  'D_4',
  'D_85',
  'D_78',
  'D_42',
  'D_52',
  'D_29'],
 'P': ['P_2', 'P_3', 'P_1'],
 'R': ['R_24',
  'R_25',
  'R_8',
  'R_26',
  'R_27',
  'R_10',
  'R_23',
  'R_2',
  'R_17',
  'R_18',
  'R_15',
  'R_20',
  'R_12',
  'R_3',
  'R_4',
  'R_6',
  'R_22',
  'R_21',
  'R_14',
  'R_16',
  'R_13',
  'R_19',
  'R_11',
  'R_9',
  'R_5',
  'R_7',
  'R_1',
  'R_28']}

In [9]:
x_train[colstartswith_dict['B']].sum(axis=1)

0         6.698634
1         9.614926
2         7.608478
3         6.309574
4         6.943610
            ...
458908    6.872459
458909    7.335395
458910    7.586269
458911    5.011741
458912    5.134372
Length: 458913, dtype: float64

In [10]:
for col_start, cols in colstartswith_dict.items():
    x_train[f"{col_start}_cols_sum"] = x_train[cols].sum(axis=1)
    x_test[f"{col_start}_cols_sum"] = x_test[cols].sum(axis=1)

In [11]:
x_train

,B_37,S_24,S_4,S_14,B_25,D_38,B_30,D_138,P_2,S_7,...,D_36_XZ,D_36_nan,D_44_R,D_44_U,D_44_nan,B_cols_sum,S_cols_sum,D_cols_sum,P_cols_sum,R_cols_sum
0,0.006462,0.008118,0.853027,0.556641,1.003906,0.193557,0.021301,0.511230,1.004883,0.081543,...,0.0,0.0,0.0,0.0,0.0,6.698634,5.836067,23.109540,1.602551,2.196609
1,0.007748,0.006310,0.758301,0.686035,0.001836,0.189822,0.088501,0.557129,0.687988,0.353027,...,0.0,0.0,0.0,0.0,0.0,9.614926,6.871033,14.755408,1.405144,2.182114
2,0.005405,0.005219,0.766602,0.284668,1.002930,0.182655,0.005821,0.854980,0.927734,0.059479,...,0.0,0.0,0.0,0.0,0.0,7.608478,5.199671,7.447959,1.571945,2.211414
3,0.004135,0.000032,0.363281,0.004623,0.533691,0.170661,0.002443,0.526367,0.700684,0.334473,...,0.0,0.0,0.0,0.0,0.0,6.309574,4.699392,9.355594,1.223454,3.884069
4,0.002968,0.002892,0.757324,0.427734,1.001953,0.213928,0.008247,0.820312,1.001953,0.144287,...,0.0,0.0,0.0,0.0,0.0,6.943610,5.843194,15.273283,1.636337,2.314814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458908,0.003967,0.005070,0.167480,0.421143,0.697266,0.186495,0.059113,0.526855,0.852051,0.724121,...,0.0,0.0,0.0,0.0,0.0,6.872459,7.019016,3.623534,1.493143,2.222829
458909,0.006248,0.007683,0.003338,0.006954,1.004883,0.180386,0.001700,0.575195,0.885254,0.286364,...,0.0,0.0,0.0,1.0,0.0,7.335395,4.177146,14.901209,1.378498,2.253111
458910,0.004993,0.003204,0.167114,0.289307,0.650879,0.178694,0.007294,0.406738,0.632324,0.346924,...,0.0,0.0,0.0,0.0,0.0,7.586269,5.408536,30.216913,1.529594,2.270559
458911,0.002348,0.005432,0.330078,0.003138,0.689941,0.184077,0.001930,0.417969,0.846191,0.172607,...,0.0,0.0,0.0,0.0,0.0,5.011741,5.187582,18.694372,1.593529,2.162937
458912,0.009079,0.009773,0.000458,0.004875,1.001953,0.172941,0.007450,0.602051,0.715332,0.281413,...,0.0,0.0,0.0,1.0,0.0,5.134372,4.197520,4.821460,1.279828,2.269429

# Using the Variable Dictionary

In [12]:
variable_dict = pd.read_excel("Data/Variable_Dictionary_Data Science Challenge.xlsx").iloc[2:].reset_index(drop=True)

In [13]:
variable_dict['Desc_first_word'] = list(map(lambda x:x.split()[0], variable_dict['Description']))

In [14]:
variable_dict.set_index("Variable Name", inplace=True)

In [15]:
variable_dict.drop(cols_not_floats, inplace=True)

In [16]:
variable_dict

                       Description Desc_first_word
Variable Name
B_1            Payment Variable 01         Payment
B_2            Payment Variable 02         Payment
B_3            Payment Variable 03         Payment
B_4            Payment Variable 04         Payment
B_5            Payment Variable 05         Payment
...                            ...             ...
S_22             Spend Variable 21           Spend
S_23             Spend Variable 22           Spend
S_24             Spend Variable 23           Spend
S_25             Spend Variable 24           Spend
S_26             Spend Variable 25           Spend

[184 rows x 2 columns]

In [17]:
variable_groups = variable_dict.groupby("Desc_first_word").groups

In [18]:
for col_start, cols in variable_groups.items():
    x_train[f"{col_start}_group"] = x_train[cols].sum(axis=1)
    x_test[f"{col_start}_group"] = x_test[cols].sum(axis=1)

In [19]:
x_train

,B_37,S_24,S_4,S_14,B_25,D_38,B_30,D_138,P_2,S_7,...,P_cols_sum,R_cols_sum,Balance_group,Bureau_group,Delinquency_group,External_group,Inquiry_group,Payment_group,Product_group,Spend_group
0,0.006462,0.008118,0.853027,0.556641,1.003906,0.193557,0.021301,0.511230,1.004883,0.081543,...,1.602551,2.196609,3.438791,3.422155,5.554138,-10.416355,1.572126,9.033210,20.784348,6.054988
1,0.007748,0.006310,0.758301,0.686035,0.001836,0.189822,0.088501,0.557129,0.687988,0.353027,...,1.405144,2.182114,5.226952,3.230743,5.906506,-21.625315,1.733452,10.459123,22.676791,7.220372
2,0.005405,0.005219,0.766602,0.284668,1.002930,0.182655,0.005821,0.854980,0.927734,0.059479,...,1.571945,2.211414,3.862859,3.644081,5.355562,-22.915026,1.537343,8.596227,18.497301,5.461120
3,0.004135,0.000032,0.363281,0.004623,0.533691,0.170661,0.002443,0.526367,0.700684,0.334473,...,1.223454,3.884069,5.714862,3.013439,5.372986,-22.696901,1.823179,8.845639,18.495665,4.903213
4,0.002968,0.002892,0.757324,0.427734,1.001953,0.213928,0.008247,0.820312,1.001953,0.144287,...,1.636337,2.314814,5.016394,3.826731,4.427289,-11.237308,6.720107,8.786059,8.322254,6.149712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458908,0.003967,0.005070,0.167480,0.421143,0.697266,0.186495,0.059113,0.526855,0.852051,0.724121,...,1.493143,2.222829,2.907753,3.183810,4.465818,-22.894159,1.582807,8.096012,16.607899,7.281040
458909,0.006248,0.007683,0.003338,0.006954,1.004883,0.180386,0.001700,0.575195,0.885254,0.286364,...,1.378498,2.253111,4.812160,3.218628,4.377789,-10.908518,1.678890,8.997097,13.497685,4.371628
458910,0.004993,0.003204,0.167114,0.289307,0.650879,0.178694,0.007294,0.406738,0.632324,0.346924,...,1.529594,2.270559,4.955704,2.990103,6.440657,1.173022,1.813699,6.654932,17.334694,5.649062
458911,0.002348,0.005432,0.330078,0.003138,0.689941,0.184077,0.001930,0.417969,0.846191,0.172607,...,1.593529,2.162937,3.601838,3.198397,5.332506,-11.244055,1.663539,8.961477,15.761972,5.374487
458912,0.009079,0.009773,0.000458,0.004875,1.001953,0.172941,0.007450,0.602051,0.715332,0.281413,...,1.279828,2.269429,3.788841,3.899389,4.410494,-22.956960,1.616972,7.881965,14.674070,4.387836

In [20]:
x_train.to_feather('Data/x_train__IterativeImputer_genFeats.ftr')
y_train.to_feather('Data/x_test__IterativeImputer_genFeats.ftr')

# Adding Null Identifiers

In [24]:
x_train.columns.values

array(['B_37', 'S_24', 'S_4', 'S_14', 'B_25', 'D_38', 'B_30', 'D_138',
       'P_2', 'S_7', 'S_25', 'S_12', 'D_99', 'B_28', 'S_21', 'B_42',
       'B_17', 'B_1', 'B_31', 'B_33', 'B_3', 'B_19', 'B_12', 'D_121',
       'D_107', 'D_79', 'B_21', 'B_29', 'D_60', 'B_26', 'B_5', 'B_9',
       'B_10', 'B_18', 'D_122', 'B_4', 'B_40', 'B_32', 'D_2', 'S_20',
       'S_13', 'R_24', 'P_3', 'R_25', 'B_14', 'D_15', 'D_68', 'D_89',
       'D_8', 'P_1', 'D_110', 'D_74', 'S_15', 'D_17', 'S_23', 'D_106',
       'B_20', 'B_35', 'D_19', 'D_88', 'D_48', 'D_34', 'B_24', 'D_98',
       'D_92', 'D_25', 'D_59', 'S_3', 'R_8', 'D_126', 'B_8', 'B_6',
       'B_38', 'R_26', 'R_27', 'R_10', 'R_23', 'R_2', 'R_17', 'R_18',
       'R_15', 'R_20', 'R_12', 'R_3', 'R_4', 'D_1', 'D_90', 'D_73',
       'D_105', 'D_67', 'B_41', 'S_22', 'D_10', 'R_6', 'R_22', 'R_21',
       'R_14', 'R_16', 'R_13', 'R_19', 'B_36', 'D_40', 'D_27', 'D_64',
       'D_133', 'D_50', 'S_9', 'D_69', 'D_65', 'D_129', 'D_22', 'B_23',
       'R_11', 'D_6', 'D_56', 'D_100', 'D_141', 'B_2', 'B_13', 'S_16',
       'S_8', 'S_11', 'S_26', 'D_87', 'D_51', 'D_123', 'D_84', 'D_18',
       'D_23', 'D_55', 'D_108', 'D_7', 'D_135', 'D_11', 'D_139', 'D_142',
       'D_31', 'D_95', 'D_61', 'D_86', 'D_5', 'D_117', 'S_2', 'D_93',
       'B_34', 'B_7', 'B_39', 'S_19', 'B_22', 'D_54', 'D_20', 'D_102',
       'D_91', 'D_32', 'D_49', 'D_26', 'D_124', 'D_130', 'D_47', 'D_9',
       'D_70', 'D_83', 'D_120', 'D_80', 'D_97', 'D_12', 'D_132', 'D_114',
       'R_9', 'D_101', 'B_15', 'R_5', 'R_7', 'B_11', 'D_96', 'D_39',
       'D_43', 'D_4', 'D_85', 'D_78', 'D_42', 'D_52', 'D_29', 'R_1',
       'R_28', 'S_5', 'D_36_CO', 'D_36_CR', 'D_36_XL', 'D_36_XM',
       'D_36_XZ', 'D_36_nan', 'D_44_R', 'D_44_U', 'D_44_nan',
       'B_cols_sum', 'S_cols_sum', 'D_cols_sum', 'P_cols_sum',
       'R_cols_sum', 'Balance_group', 'Bureau_group', 'Delinquency_group',
       'External_group', 'Inquiry_group', 'Payment_group',
       'Product_group', 'Spend_group'], dtype=object)

In [26]:
orig_train.columns.values

array(['B_37', 'S_24', 'S_4', 'S_14', 'B_25', 'D_38', 'B_30', 'D_138',
       'P_2', 'S_7', 'S_25', 'S_12', 'D_99', 'D_36', 'B_28', 'S_21',
       'B_42', 'B_17', 'B_1', 'B_31', 'B_33', 'B_3', 'B_19', 'B_12',
       'D_121', 'D_107', 'D_79', 'B_21', 'B_29', 'D_60', 'B_26', 'B_5',
       'B_9', 'B_10', 'B_18', 'D_122', 'B_4', 'B_40', 'B_32', 'D_2',
       'S_20', 'S_13', 'R_24', 'P_3', 'R_25', 'B_14', 'D_15', 'D_68',
       'D_89', 'D_8', 'P_1', 'D_110', 'D_74', 'S_15', 'D_17', 'S_23',
       'D_106', 'B_20', 'B_35', 'D_19', 'D_88', 'D_48', 'D_34', 'D_44',
       'B_24', 'D_98', 'D_92', 'D_25', 'D_59', 'S_3', 'R_8', 'D_126',
       'B_8', 'B_6', 'B_38', 'R_26', 'R_27', 'R_10', 'R_23', 'R_2',
       'R_17', 'R_18', 'R_15', 'R_20', 'R_12', 'R_3', 'R_4', 'D_1',
       'D_90', 'D_73', 'D_105', 'D_67', 'B_41', 'S_22', 'D_10', 'R_6',
       'R_22', 'R_21', 'R_14', 'R_16', 'R_13', 'R_19', 'B_36', 'D_40',
       'D_27', 'D_64', 'D_133', 'D_50', 'S_9', 'D_69', 'D_65', 'D_129',
       'D_22', 'B_23', 'R_11', 'D_6', 'D_56', 'D_100', 'D_141', 'B_2',
       'B_13', 'S_16', 'S_8', 'S_11', 'S_26', 'D_87', 'D_51', 'D_123',
       'D_84', 'D_18', 'D_23', 'D_55', 'D_108', 'D_7', 'D_135', 'D_11',
       'D_139', 'D_142', 'D_31', 'D_95', 'D_61', 'D_86', 'D_5', 'D_117',
       'S_2', 'D_93', 'B_34', 'B_7', 'B_39', 'S_19', 'B_22', 'D_54',
       'D_20', 'D_102', 'D_91', 'D_32', 'D_49', 'D_26', 'D_124', 'D_130',
       'D_47', 'D_9', 'D_70', 'D_83', 'D_120', 'D_80', 'D_97', 'D_12',
       'D_132', 'D_114', 'R_9', 'D_101', 'B_15', 'R_5', 'R_7', 'B_11',
       'D_96', 'D_39', 'D_43', 'D_4', 'D_85', 'D_78', 'D_42', 'D_52',
       'D_29', 'R_1', 'R_28', 'S_5'], dtype=object)

In [29]:
trainNa = orig_train.drop(['D_36', 'D_44'], axis=1).isna()
trainNa.columns = [f"{c}_missing" for c in trainNa.columns]

train = pd.concat([x_train, trainNa], axis=1)

testNa = orig_test.drop(['D_36', 'D_44'], axis=1).isna()
testNa.columns = [f"{c}_missing" for c in testNa.columns]

test = pd.concat([x_test, testNa], axis=1)

In [30]:
train

,B_37,S_24,S_4,S_14,B_25,D_38,B_30,D_138,P_2,S_7,...,D_43_missing,D_4_missing,D_85_missing,D_78_missing,D_42_missing,D_52_missing,D_29_missing,R_1_missing,R_28_missing,S_5_missing
0,0.006462,0.008118,0.853027,0.556641,1.003906,0.193557,0.021301,0.511230,1.004883,0.081543,...,True,False,False,False,False,False,False,False,False,False
1,0.007748,0.006310,0.758301,0.686035,0.001836,0.189822,0.088501,0.557129,0.687988,0.353027,...,True,False,False,False,False,False,False,False,False,False
2,0.005405,0.005219,0.766602,0.284668,1.002930,0.182655,0.005821,0.854980,0.927734,0.059479,...,True,False,False,False,False,False,False,False,False,False
3,0.004135,0.000032,0.363281,0.004623,0.533691,0.170661,0.002443,0.526367,0.700684,0.334473,...,True,False,False,False,False,False,False,False,False,False
4,0.002968,0.002892,0.757324,0.427734,1.001953,0.213928,0.008247,0.820312,1.001953,0.144287,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458908,0.003967,0.005070,0.167480,0.421143,0.697266,0.186495,0.059113,0.526855,0.852051,0.724121,...,True,False,False,False,False,False,False,False,False,False
458909,0.006248,0.007683,0.003338,0.006954,1.004883,0.180386,0.001700,0.575195,0.885254,0.286364,...,True,False,False,False,False,False,False,False,False,False
458910,0.004993,0.003204,0.167114,0.289307,0.650879,0.178694,0.007294,0.406738,0.632324,0.346924,...,True,False,False,False,False,False,False,False,False,False
458911,0.002348,0.005432,0.330078,0.003138,0.689941,0.184077,0.001930,0.417969,0.846191,0.172607,...,True,False,False,False,False,False,False,False,False,False
458912,0.009079,0.009773,0.000458,0.004875,1.001953,0.172941,0.007450,0.602051,0.715332,0.281413,...,True,False,False,False,False,False,False,False,False,False

In [31]:
train.to_feather('Data/x_train__IterativeImputer_genFeats.ftr')
test.to_feather('Data/x_test__IterativeImputer_genFeats.ftr')

# Auto Feat

In [21]:
from autofeat import AutoFeatClassifier

In [28]:
model = AutoFeatClassifier(n_jobs=8, verbose=1)

In [29]:
df = model.fit_transform(x_train, y_train)

/home/jindalmadhur26/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[AutoFeat] The 2 step feature engineering process could generate up to 1060696 features.
[AutoFeat] With 458913 data points this new feature matrix would use about 1947.07 gb of space.
[feateng] Step 1: transformation of original features
[feateng] Generated 867 transformed features from 208 original features - done.
[feateng] Step 2: first combination of features

/home/jindalmadhur26/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/jindalmadhur26/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]

KeyboardInterrupt: